# Derby DataBase용
#spring:
#  datasource:
#    hikari:
#      maximum-pool-size: 10
#    url: jdbc:derby:memory:testdb;create=true
#    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
#    username: sa
#    password: password