spring:
  profiles:
    active: mysql
  application:
    name: ex-batch
# jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      name: JPA_ITEM_WRITER_JOB